name: Lint golangci

on:
  pull_request:
    branches:
      - main
      - feat/**
  workflow_dispatch:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lifecycle-manager
        uses: actions/checkout@v4
        with:
          path: lifecycle-manager

      - uses: actions/setup-go@v5
        with:
          go-version-file: './lifecycle-manager/go.mod'
          cache: false

      - name: Get configuration
        uses: ./lifecycle-manager/.github/actions/get-configuration
        id: configuration

      - name: golangci-lint
        uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager

      - name: golangci-lint for api module
        uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/api

      - name: golangci-lint for maintenancewindows module
        uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
        with:
          version: v${{ steps.configuration.outputs.golangci_lint_version }}
          args: --verbose
          working-directory: ./lifecycle-manager/maintenancewindows
